name: ksqlDB Migrations Apply
description: apply ksqlDB schema with GitHub actions
inputs:
  config:
    description: Path to config file
    default: /github/workspace/ksql-migrations.properties
runs:
  using: docker
  image: docker://confluentinc/ksqldb-cli:0.17.0
  args:
    - sh
    - -c
    - if ksql-migrations -c ${{ inputs.config }} applay -a | grep -q Successfully; then exit 0 ; else echo ERROR exit 1 ; fi
    #- ksql-migrations
    #- apply
    #- -a
    #- -c
    #- ${{ inputs.config }}