

CREATE STREAM PAGEVIEWSREGION_STREAM  (USERID STRING  KEY, PAGEID BIGINT,  REGIONID STRING, GENDER STRING) 
WITH (KAFKA_TOPIC='pageviews_region', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO');



CREATE STREAM USER_PAGEVIEWSREGION
  AS SELECT  USERID,PAGEID, REGIONID, GENDER
    FROM PAGEVIEWSREGION_STREAM
    WHERE regionid LIKE '%_8' OR regionid LIKE '%_9'
EMIT CHANGES;
