CREATE STREAM STM_DEPARTMENTS_RAW (DEPT_NO VARCHAR, DEPT_NAME VARCHAR) WITH (KAFKA_TOPIC='STM_DEPARTMENTS_RAW', VALUE_FORMAT='JSON', PARTITIONS=1, REPLICAS=1, KEY='DEPT_NO');

CREATE STREAM STM_DEPARTMENTS_WITH_KEY AS SELECT UCASE(DEPT_NO) AS DEPT_NO, UCASE(DEPT_NAME) AS DEPT_NAME FROM STM_DEPARTMENTS_RAW PARTITION BY DEPT_NO;