

CREATE STREAM PAGEVIEWSREGION_STREAM  (USERID STRING PRIMARY KEY, PAGEID BIGINT,  REGIONID STRING) 
WITH (KAFKA_TOPIC='pageviews_region', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO');



CREATE STREAM USER_PAGEVIEWSREGION
  AS SELECT  USERID,PAGEID, REGIONID
    FROM PAGEVIEWSREGION_STREAM
    WHERE regionid LIKE '%_8' OR regionid LIKE '%_9'
EMIT CHANGES;
