CREATE STREAM PAGEVIEWS_STREAM (VIEWTIME BIGINT, USERID STRING, PAGEID STRING) 
WITH (KAFKA_TOPIC='test_topic', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO');

CREATE TABLE USERS_TABLE (ID STRING PRIMARY KEY, REGISTERTIME BIGINT, USERID STRING, REGIONID STRING, GENDER STRING) 
WITH (KAFKA_TOPIC='users2', KEY_FORMAT='KAFKA', VALUE_FORMAT='AVRO');



CREATE STREAM user_pageviews
  AS SELECT users_table.id AS USERID, PAGEID, REGIONID, GENDER
    FROM PAGEVIEWS_STREAM
    LEFT JOIN USERS_TABLE ON PAGEVIEWS_STREAM.USERID = USERS_TABLE.ID
EMIT CHANGES;
